/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.labeling;

import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MyDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  @Override
  public Image getImage(final Object object) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
}
